version: '3.5'

services:
  postgres:
    container_name: postgres_database_livro_api
    image: postgres
    environment:
      POSTGRES_USER: livroAPI
      POSTGRES_PASSWORD: minhaSenhaSuperComplexa
      POSTGRES_DB: livroDB
      PGDATA: /data/postgres
    volumes:
       - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin-password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  backend:
    container_name: backend_container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APPLICATION_PORT: "8080"
      DB_HOST: "postgres"
      DB_NAME: "livroDB"
      DB_USERNAME: "livroAPI"
      DB_PASSWORD: "minhaSenhaSuperComplexa"
      DB_PORT: "5432"
    ports:
      - "8080:8080"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
